export const YTDLP_OPTIONS = {
  general: [
    { flag: '--abort-on-error', type: 'boolean', label: 'Abort on Error', description: 'Abort if an error occurs', category: 'general' },
    { flag: '--color', type: 'choice', label: 'Color', description: 'Color output', param: 'WHEN', choices: ['always', 'auto', 'never'], category: 'general' },
    { flag: '--compat-options', type: 'string', label: 'Compat Options', description: 'Compatibility options', param: 'OPTS', category: 'general' },
    { flag: '--config-location', type: 'string', label: 'Config Location', description: 'Path to config file', param: 'PATH', category: 'general' },
    { flag: '--flat-playlist', type: 'boolean', label: 'Flat Playlist', description: 'Do not extract URLs of playlist videos', category: 'general' },
    { flag: '--ignore-errors', type: 'boolean', label: 'Ignore Errors', description: 'Continue on download errors', category: 'general' },
    { flag: '--no-overwrites', type: 'boolean', label: 'No Overwrites', description: 'Do not overwrite existing files', category: 'general' },
    { flag: '--restrict-filenames', type: 'boolean', label: 'Restrict Filenames', description: 'Restrict filenames to ASCII', category: 'general' },
    { flag: '--no-cache-dir', type: 'boolean', label: 'No Cache Dir', description: 'Disable filesystem caching', category: 'general' },
    { flag: '--cache-dir', type: 'string', label: 'Cache Dir', description: 'Cache directory location', param: 'DIR', category: 'general' },
  ],
  videoSelection: [
    { flag: '--playlist-start', type: 'number', label: 'Playlist Start', description: 'Starting index (1-based)', param: 'N', category: 'videoSelection' },
    { flag: '--playlist-end', type: 'number', label: 'Playlist End', description: 'Ending index', param: 'N', category: 'videoSelection' },
    { flag: '--playlist-items', type: 'string', label: 'Playlist Items', description: 'Specific playlist items to download', param: 'ITEM_SPEC', category: 'videoSelection' },
    { flag: '--match-title', type: 'string', label: 'Match Title', description: 'Download only matching titles (regex)', param: 'REGEX', category: 'videoSelection' },
    { flag: '--reject-title', type: 'string', label: 'Reject Title', description: 'Skip matching titles (regex)', param: 'REGEX', category: 'videoSelection' },
    { flag: '--max-downloads', type: 'number', label: 'Max Downloads', description: 'Maximum number of videos to download', param: 'N', category: 'videoSelection' },
    { flag: '--min-filesize', type: 'string', label: 'Min Filesize', description: 'Minimum filesize (e.g. 50M, 1G)', param: 'SIZE', category: 'videoSelection' },
    { flag: '--max-filesize', type: 'string', label: 'Max Filesize', description: 'Maximum filesize', param: 'SIZE', category: 'videoSelection' },
    { flag: '--date', type: 'string', label: 'Date', description: 'Download only videos uploaded on this date', param: 'DATE', category: 'videoSelection' },
    { flag: '--datebefore', type: 'string', label: 'Date Before', description: 'Download only videos uploaded before this date', param: 'DATE', category: 'videoSelection' },
    { flag: '--dateafter', type: 'string', label: 'Date After', description: 'Download only videos uploaded after this date', param: 'DATE', category: 'videoSelection' },
    { flag: '--no-playlist', type: 'boolean', label: 'No Playlist', description: 'Download only the video, not the playlist', category: 'videoSelection' },
    { flag: '--yes-playlist', type: 'boolean', label: 'Yes Playlist', description: 'Download the playlist', category: 'videoSelection' },
  ],
  downloadOptions: [
    { flag: '--limit-rate', type: 'string', label: 'Limit Rate', description: 'Download speed limit (e.g. 500K, 2M)', param: 'RATE', category: 'downloadOptions' },
    { flag: '--retries', type: 'number', label: 'Retries', description: 'Number of retries (default 10)', param: 'N', category: 'downloadOptions' },
    { flag: '--fragment-retries', type: 'number', label: 'Fragment Retries', description: 'Number of fragment retries', param: 'N', category: 'downloadOptions' },
    { flag: '--skip-unavailable-fragments', type: 'boolean', label: 'Skip Unavailable Fragments', description: 'Skip unavailable fragments', category: 'downloadOptions' },
    { flag: '--buffer-size', type: 'string', label: 'Buffer Size', description: 'Buffer size (e.g. 1024)', param: 'SIZE', category: 'downloadOptions' },
    { flag: '--http-chunk-size', type: 'string', label: 'HTTP Chunk Size', description: 'HTTP chunk size', param: 'SIZE', category: 'downloadOptions' },
    { flag: '--no-resume-begin', type: 'boolean', label: 'No Resume Begin', description: 'Do not resume from beginning of URL', category: 'downloadOptions' },
  ],
  filesystem: [
    { flag: '-o', type: 'string', label: 'Output Template', description: 'Output filename template', param: 'TEMPLATE', category: 'filesystem' },
    { flag: '--output-na-placeholder', type: 'string', label: 'Output NA Placeholder', description: 'Placeholder for unavailable fields', param: 'TEXT', category: 'filesystem' },
    { flag: '--restrict-filenames', type: 'boolean', label: 'Restrict Filenames', description: 'Restrict filenames to ASCII characters', category: 'filesystem' },
    { flag: '--windows-filenames', type: 'boolean', label: 'Windows Filenames', description: 'Force Windows-compatible filenames', category: 'filesystem' },
    { flag: '--trim-filename', type: 'number', label: 'Trim Filename', description: 'Max filename length', param: 'LENGTH', category: 'filesystem' },
    { flag: '--paths', type: 'string', label: 'Paths', description: 'Output directory paths', param: 'TYPE:PATH', category: 'filesystem' },
    { flag: '--force-keyframes-at-cut', type: 'boolean', label: 'Force Keyframes at Cut', description: 'Force keyframes at cut points', category: 'filesystem' },
  ],
  thumbnails: [
    { flag: '--write-thumbnail', type: 'boolean', label: 'Write Thumbnail', description: 'Write thumbnail to disk', category: 'thumbnails' },
    { flag: '--write-all-thumbnails', type: 'boolean', label: 'Write All Thumbnails', description: 'Write all thumbnail formats', category: 'thumbnails' },
    { flag: '--list-thumbnails', type: 'boolean', label: 'List Thumbnails', description: 'List available thumbnails', category: 'thumbnails' },
    { flag: '--convert-thumbnails', type: 'choice', label: 'Convert Thumbnails', description: 'Convert thumbnail format', param: 'FORMAT', choices: ['jpg', 'png', 'webp'], category: 'thumbnails' },
  ],
  subtitles: [
    { flag: '--write-subs', type: 'boolean', label: 'Write Subs', description: 'Write subtitle file', category: 'subtitles' },
    { flag: '--write-auto-subs', type: 'boolean', label: 'Write Auto Subs', description: 'Write automatically generated subtitles', category: 'subtitles' },
    { flag: '--all-subs', type: 'boolean', label: 'All Subs', description: 'Download all available subtitles', category: 'subtitles' },
    { flag: '--sub-langs', type: 'string', label: 'Sub Languages', description: 'Languages to download (comma-separated)', param: 'LANGS', category: 'subtitles' },
    { flag: '--sub-format', type: 'string', label: 'Sub Format', description: 'Subtitle format (srt, vtt, ass)', param: 'FORMAT', category: 'subtitles' },
    { flag: '--embed-subs', type: 'boolean', label: 'Embed Subs', description: 'Embed subtitles in video', category: 'subtitles' },
  ],
  postProcessing: [
    { flag: '-x', type: 'boolean', label: 'Extract Audio', description: 'Convert video to audio', category: 'postProcessing' },
    { flag: '--audio-format', type: 'choice', label: 'Audio Format', description: 'Audio format to convert to', param: 'FORMAT', choices: ['mp3', 'm4a', 'opus', 'flac', 'wav'], category: 'postProcessing' },
    { flag: '--audio-quality', type: 'string', label: 'Audio Quality', description: 'Audio quality (0-10)', param: 'QUALITY', category: 'postProcessing' },
    { flag: '--recode-video', type: 'choice', label: 'Recode Video', description: 'Recode video format', param: 'FORMAT', choices: ['mp4', 'webm', 'mkv', 'avi'], category: 'postProcessing' },
    { flag: '--embed-thumbnail', type: 'boolean', label: 'Embed Thumbnail', description: 'Embed thumbnail into file', category: 'postProcessing' },
    { flag: '--embed-metadata', type: 'boolean', label: 'Embed Metadata', description: 'Embed metadata into file', category: 'postProcessing' },
    { flag: '--embed-chapters', type: 'boolean', label: 'Embed Chapters', description: 'Embed chapter markers', category: 'postProcessing' },
    { flag: '--sponsorblock-remove', type: 'string', label: 'SponsorBlock Remove', description: 'Remove sponsor segments', param: 'CATEGORIES', category: 'postProcessing' },
    { flag: '--ppa', type: 'string', label: 'PPA Args', description: 'Post-processor arguments', param: 'ARGS', category: 'postProcessing' },
    { flag: '--exec', type: 'string', label: 'Exec', description: 'Execute command after download', param: 'CMD', category: 'postProcessing' },
  ],
  network: [
    { flag: '--proxy', type: 'string', label: 'Proxy', description: 'Proxy URL', param: 'URL', category: 'network' },
    { flag: '--socket-timeout', type: 'number', label: 'Socket Timeout', description: 'Socket timeout in seconds', param: 'SECONDS', category: 'network' },
    { flag: '--source-address', type: 'string', label: 'Source Address', description: 'Client IP address', param: 'IP', category: 'network' },
    { flag: '--force-ipv4', type: 'boolean', label: 'Force IPv4', description: 'Use IPv4 only', category: 'network' },
    { flag: '--force-ipv6', type: 'boolean', label: 'Force IPv6', description: 'Use IPv6 only', category: 'network' },
    { flag: '--enable-file-urls', type: 'boolean', label: 'Enable File URLs', description: 'Allow file:// URLs', category: 'network' },
    { flag: '--cookies', type: 'string', label: 'Cookies File', description: 'Path to cookies file', param: 'FILE', category: 'network' },
    { flag: '--cookies-from-browser', type: 'string', label: 'Cookies from Browser', description: 'Extract cookies from browser', param: 'BROWSER', category: 'network' },
    { flag: '--no-check-certificates', type: 'boolean', label: 'No Check Certificates', description: 'Skip HTTPS certificate validation', category: 'network' },
  ],
  verbosity: [
    { flag: '-q', type: 'boolean', label: 'Quiet', description: 'Suppress output', category: 'verbosity' },
    { flag: '-s', type: 'boolean', label: 'Simulate', description: 'Do not download', category: 'verbosity' },
    { flag: '--verbose', type: 'boolean', label: 'Verbose', description: 'Print debug info', category: 'verbosity' },
    { flag: '--print', type: 'string', label: 'Print', description: 'Print field(s)', param: 'FIELD', category: 'verbosity' },
    { flag: '--dump-json', type: 'boolean', label: 'Dump JSON', description: 'Output video info as JSON', category: 'verbosity' },
    { flag: '--dump-single-json', type: 'boolean', label: 'Dump Single JSON', description: 'Output as single JSON', category: 'verbosity' },
    { flag: '--print-traffic', type: 'boolean', label: 'Print Traffic', description: 'Display HTTP traffic', category: 'verbosity' },
    { flag: '--call-home', type: 'boolean', label: 'Call Home', description: 'Contact yt-dlp server', category: 'verbosity' },
    { flag: '--no-call-home', type: 'boolean', label: 'No Call Home', description: 'Do not contact yt-dlp server', category: 'verbosity' },
  ],
};
